name: repo-spector
# https://github.com/4okimi7uki/repo-spector

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          repository: da-pinci/da-pinci
          token: ${{ secrets.GH_TOKEN }}
          ref: main

      - name: Download repo-spector binary from GitHub Release
        shell: bash
        run: |
          curl -L https://github.com/4okimi7uki/repo-spector/releases/latest/download/repo-spector -o repo-spector
          chmod +x ./repo-spector

      - name: Run repo-spector CLI
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p output
          ./repo-spector

      - name: Commit and Push updated SVGs
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update: language stats svg"
            git push
          fi
